The NumPy library is the core library for scientific computing in
Python. It provides a high-performance multidimensional array
object, and tools for working with these arrays.

---

import numpy as np

Use the following import convention:

In [0]:
import numpy as np

In [89]:
# Creating Array
a = np.array([1,2,3]) #one dimensional array
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]],
dtype = float)
print(a)
print(b)
print(c)

[1 2 3]
[[1.5 2.  3. ]
 [4.  5.  6. ]]
[[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]


## Initial Placeholders

In [90]:
# Create an array of zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [91]:
# Create an array of ones
np.ones((3,4), dtype = np.int16)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [92]:
#Create an array of evenly spaced values (step value)
d = np.arange(10,25,5) 
print(d)

[10 15 20]


In [93]:
# Create an array of evenly spaced values (number of samples)
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [94]:
# Create a constant array
e = np.full((2,2),7)
print(e)

[[7 7]
 [7 7]]


In [95]:
# Create a 2X2 identity matrix
f = np.eye(2)
print(f)

[[1. 0.]
 [0. 1.]]


In [96]:
# Create an array with random values
np.random.random((2,2))

array([[0.16349153, 0.45692408],
       [0.5095391 , 0.47522291]])

In [97]:
# Create an empty array
np.empty((3,2))

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])

# I/O

## Saving & Loading On Disk

In [98]:
np.save('my_array', a)
np.savez('array.npz', a, b)
np.load('my_array.npy')

array([1, 2, 3])

## Inspecting Your Array

In [99]:
# Array dimensions
a.shape

(3,)

In [100]:
# Length of array
# a.size
print(len(a))

3


In [101]:
# Number of array dimensions
b.ndim

2

In [102]:
# Number of array elements
e.size

4

In [103]:
# Data type of array elements
b.dtype

dtype('float64')

In [104]:
# Name of data type
b.dtype.name

'float64'

In [105]:
# Convert an array to a different type
b.astype(int)

array([[1, 2, 3],
       [4, 5, 6]])

# Array Mathematics

## Arithmetic Operations

In [106]:
# Subtraction
g = a - b
print(g)

[[-0.5  0.   0. ]
 [-3.  -3.  -3. ]]


In [107]:
# Substrcation
np.subtract(a,b)

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [108]:
# Addition
h = a + b
print(h)

[[2.5 4.  6. ]
 [5.  7.  9. ]]


In [109]:
# Addition
np.add(a,b)

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [110]:
# Division
i = a/b
print(i)

[[0.66666667 1.         1.        ]
 [0.25       0.4        0.5       ]]


In [111]:
# Divisoin
np.divide(a,b)

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [112]:
# Multiplication
k = a*b
print(k)

[[ 1.5  4.   9. ]
 [ 4.  10.  18. ]]


In [113]:
# Multiplication
np.multiply(a,b)

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [114]:
# Exponentiation
np.exp(b)

array([[  4.48168907,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [115]:
# Square root
np.sqrt(b)

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [116]:
# Print sines of an array
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [117]:
# Element-wise cosine
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [118]:
# Element-wise natural logarithm
np.log(a)

array([0.        , 0.69314718, 1.09861229])

In [119]:
# Dot product
e.dot(f)

array([[7., 7.],
       [7., 7.]])

## Comparison

In [120]:
# Element-wise comparison
a == b

array([[False,  True,  True],
       [False, False, False]])

In [121]:
# Element-wise comparison
a < 2

array([ True, False, False])

In [122]:
# Array-wise comparison
np.array_equal(a, b)

False

## Aggregate Functions

In [123]:
# Array-wise sum
a.sum()

6

In [124]:
# Array-wise minimum value
a.min()

1

In [125]:
# Maximum value of an array row
b.max(axis=0)

array([4., 5., 6.])

In [126]:
# Cumulative sum of the elements
b.cumsum(axis=1)

array([[ 1.5,  3.5,  6.5],
       [ 4. ,  9. , 15. ]])

In [127]:
# Mean
a.mean()

2.0

In [0]:
# Median
a.median()

In [0]:
#Correlation coefficient
a.corrcoef()

In [0]:
#Standard deviation
np.std(b)

## Copying Arrays

In [129]:
# Create a view of the array with the same data
h = a.view()
print(h)

[1 2 3]


In [130]:
# Create a copy of the array
np.copy(a)

array([1, 2, 3])

In [131]:
# Create a deep copy of the array
h = a.copy()
print(h)

[1 2 3]


## Sorting Arrays

In [132]:
# Sort an array
print(a.sort())

None


In [133]:
#Sort the elements of an array's axis
print(c.sort(axis=0))

None


## Subsetting, Slicing, Indexing

### Subsetting

In [134]:
#Select the element at the 2nd index
a[2]

3

In [136]:
# Select the element at row 1 column 2 (equivalent to b[1][2])
b[1,2]

6.0

### Slicing

In [137]:
# Select items at index 0 and 1
a[0:2]

array([1, 2])

In [138]:
# Select items at rows 0 and 1 in column 1
b[0:2,1]

array([2., 5.])

In [140]:
# Select all items at row 0 (equivalent to b[0:1, :])
b[:1]

array([[1.5, 2. , 3. ]])

In [141]:
# Reversed array a
a[ : :-1]

array([3, 2, 1])

## Array Manipulation

In [143]:
#Transposing Array
i = np.transpose(b)
i.T

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [145]:
# Changing Array Shape
b.ravel()

array([1.5, 2. , 3. , 4. , 5. , 6. ])

In [148]:
g.reshape(3,-2)

array([[-0.5,  0. ],
       [ 0. , -3. ],
       [-3. , -3. ]])

In [0]:
## Adding/Removing Elements
h.resize((2,6))


In [150]:
# Combining Arrays
np.concatenate((a,d),axis=0)

array([ 1,  2,  3, 10, 15, 20])