# NumPy : Numeric Python

---

***NumPy is the package of scientific computing***

---

NumPy is the fundamental package for scientific computing with Python. It contains among other things:

*   a powerful N-dimensional array (Ndarray) object
*   sophisticated (broadcasting) functions
*   tools for integrating C/C++ and Fortran code
*   useful linear algebra, Fourier transform, and random number capabilities

Besides its obvious scientific uses, **NumPy** can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows **NumPy** to seamlessly and speedily integrate with a wide variety of databases.

**NumPy** is licensed under the ***BSD license***, enabling reuse with few restrictions.


---

NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In NumPy dimensions are called ***axes***.

NumPy’s array class is called ***ndarray***. It is also known by the alias array.



**Ndarray - NumPy Array**

---

The Ndarray is a multi-dimenstional array object consisting of two parts -- the actual data, some metadata which describes the stored data. They are indexed just like sequence are in python, starting from 0.

*   Each element of Ndarray is an object of data-type object (called dtype)
*   An item extracted form **ndarray**, is represented by a python object of an array scaler type 

---




**The more important attributes of an ndarray object are:**

---



***ndarray.ndim*** : 
      the number of axes (dimensions) of the array.

***ndarray.shape*** : 
the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the number of axes, ndim.

***ndarray.size*** : 
the total number of elements of the array. This is equal to the product of the elements of shape.

***ndarray.dtype*** :
an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.

***ndarray.itemsize*** :
the size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.itemsize.
 
 ***ndarray.data*** : 
 the buffer containing the actual elements of the array. Normally, we won’t need to use this attribute because we will access the elements in an array using indexing facilities.

---



**An Example:**

In [0]:
import numpy as np
a = np.arange(15)# Create one-dimenstional array using arange() function
print(a)

#check the dimenstion of array
print(a.ndim) 

#Reshape array 
a= a.reshape(3,5)
print(a)

#check the shape of array (rows, columns)
print(a.shape)

#check the size of array (the total number of elements of the array)
print(a.size)

#check data type of array
print(a.dtype)

#check itemsize of array
print(a.itemsize)

#check type of array
print(type(a))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
1
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
15
int64
8
<class 'numpy.ndarray'>


**Creating a NumPy Array - Single Dimensional Array**

---

There are several ways to create arrays.

For example, you can create an array from a regular Python list or tuple using the array function. The type of the resulting array is deduced from the type of the elements in the sequences.


In [0]:
import numpy as np

a = np.array([2,3,4])
print("array:", a)
print(a.dtype)

b = np.array([1.0, 2.5, 3.0])
print("array:", b)
print(b.dtype)

array: [2 3 4]
int64
array: [1.  2.5 3. ]
float64


**Note:** A frequent error consists in calling array with multiple numeric arguments, rather than providing a single list of numbers as an argument.

---



In [0]:
a = np.array(1,2,3,4) #Wrong
print(a)

a = np.array([1,2,3,4])  # RIGHT

ValueError: ignored

**Creating an array of numbers of a specific range or using range function**

---

Example:

In [0]:
import numpy as np

a = np.arange(10, 100, 2) # np.arange(start, stop, step)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56
 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98]


**Creating a linearly spaced vector, with spacing**

---

Example:


In [0]:
import numpy as np

vector = np.linspace(0, 20, 5)
print(vector)

[ 0.  5. 10. 15. 20.]


**Creating an array using existing data**

---
*   **numpy.asarray** - used for converting Python sequence into ndarrays
*  ** syntax: **numpy.asarray(a, dtype = None, order = None)

Example:



In [0]:
import numpy

x = [1,2,3]
a = numpy.asarray(x)
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


**Reshape or Restructuring a NumPy Array:**

---

One-dimensional arrays are then printed as **rows**, bidimensionals (two dimensional) as **matrices ** and tridimensionals (three dimensional)as lists of **matrices**.

In [0]:
import numpy as np

# one dimensional or 1D array
a = np.arange(6)
print(a)
print()

#bidimensional or two dimensional array or 2D array
b = np.arange(12)
print(b.reshape(3,4))
print()

#three dimensional or 3D array
c = np.arange(24)
print(c.reshape(2,3,4))


[0 1 2 3 4 5]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


**NumPy Attributes:**

The function ***zeros*** creates an array full of zeros, the function ***ones*** creates an array full of ones, and the function ***empty*** creates an array whose initial content is random and depends on the state of the memory. By default, the dtype of the created array is float64.

---


In [0]:
a = np.zeros( (3,4) )
print(a)
print()

b = np.ones( (2,3,4), dtype=np.int16 )
print(b)
print()

c = np.empty((2,3))
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]

[[0.0e+000 4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323 2.5e-323]]


**Flatten the 3D array to get back the linear array:** : ***ravel() function***

---



In [0]:
b = np.ones( (2,3,4))
print(b)
print()

print(b.ravel())

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


**Basic Operation** 

---

Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.

In [0]:
import numpy as np

a = np.array([10,20,30,40])

b = np.arange(4)

c = a + b # addition
print(c)

d = a - b # subtraction
print(d)

e = a * b # multiplication
print(e)

print(b**2) # expontial

print(a<25) # Boolen values

print(np.sqrt(a)) #Square root value of each element of array




[10 21 32 43]
[10 19 28 37]
[  0  20  60 120]
[0 1 4 9]
[ True  True False False]
[3.16227766 4.47213595 5.47722558 6.32455532]


Many unary operations, such as computing the sum of all the elements in the array, are implemented as methods of the ndarray class.

---



In [0]:
a = np.random.random((2,3))
print(a)

print("sum:", a.sum())

print("min", a.min())

print("max:", a.max())

[[0.17088387 0.85938958 0.03122912]
 [0.05580133 0.63799616 0.89100346]]
sum: 2.646303515378495
min 0.03122912047934112
max: 0.8910034603138379


By default, these operations apply to the array as though it were a list of numbers, regardless of its shape. However, by specifying the axis parameter you can apply an operation along the specified axis of an array:

---



In [0]:
b = np.arange(12).reshape(3,4)

print(b)

# sum of each column
print(b.sum(axis = 0))

# min of each row
print(b.min(axis = 1))

#cumulative sum along each row
print(b.cumsum(axis = 1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]
[0 4 8]
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


#Indexing, Slicing and Iterating

---

One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.

In [0]:
import numpy as np

a = np.arange(10)**3
print(a)

[  0   1   8  27  64 125 216 343 512 729]


In [0]:
# indexing
a[2]

8


In [0]:
#slicing
a[1:5]

array([ 1,  8, 27, 64])

In [0]:
print(a[:5])

[ 0  1  8 27 64]


In [0]:
#Reverse an array
print(a[::-1])

[729 512 343 216 125  64  27   8   1   0]


In [0]:
#interating
for i in a:
  print(i**(1/3))


0.0
1.0
2.0
3.0
3.9999999999999996
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


Extracting specific rows and columns using slicing

---



In [0]:
import numpy as np

a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a)

# Slice first two rows and first two columns
print(a[0:2,0:2]) 

[[1 2 3]
 [3 4 5]
 [4 5 6]]
[[1 2]
 [3 4]]


**Reading and Writing from File:**

---

NumPy provides the option of importing data from files directly into ndarray using the ***loadtxt () ***function

The savetxt() function can be used to write data from an array into the text file

In [0]:
arr = np.loadtxt('filex.txt')
np.savetxt('newfilex.txt')